<a href="https://colab.research.google.com/github/spooozy/Machine-learning-methods/blob/main/lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import math
import re
import numpy as np
import random

### Часть 1
1. Вывести  на  экран  все  простые  числа  в  заданном  диапазоне
(диапазон вводится с клавиатуры).

In [ ]:
print("Task 1.1")
print("-" * 36)
input_check = False
while not input_check:
  try:
    a, b = int(input("Enter number 1: ")), int(input("Enter number 2: "))
    input_check = True
    if a < 2 or b < 2:
      print("Numbers must be >= 2. Try again")
      input_check = False
    elif a >= b:
      print("Number 1 must be less than number 2. Try again")
      input_check = False
  except ValueError as error:
    print(error)

primes = []
if a <= 2 <= b:
  primes.append(2)

start = max(a, 3)
if start % 2 == 0:
  start += 1

end = b
if end % 2 == 0:
  end -= 1

for i in range(start, end + 1, 2):
  i_sqrt = int(round(math.sqrt(i)))
  is_prime = True
  for j in range(3, i_sqrt + 1, 2):
    if i % j == 0:
      is_prime = False
      break
  if is_prime:
    primes.append(i)

print(primes)

Enter number 1: 10
Enter number 2: 20
[11, 13, 17, 19]


2. С клавиатуры вводится текст, определить, сколько в нём гласных,
а сколько согласных. В случае равенства вывести на экран все гласные
буквы. Посчитать количество слов в тексте

In [ ]:
print("Task 1.2")
print("-" * 36)
vowels = {'a', 'e', 'i', 'o', 'u'}
consonants = {'b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'q', 'r', 's', 't', 'v', 'w', 'x', 'z'}
res = []
consonants_num = 0
text = input("Enter text: ")
words = re.split(r'[.,!?()\[\]|/\\\s]+', text)
words = [word for word in words if word]
for word in words:
  for letter in word:
    letter_low = letter.lower()
    if letter_low in vowels:
      res.append(letter)
    elif letter_low in consonants:
      consonants_num += 1
print(f"- Word count: {len(words)}\n- Vowels count: {len(res)}\n- Consonants count: {consonants_num}")
if len(res) == consonants_num != 0:
  print(f"- Vowels: {res}")

Enter text: aaa.bb.c.uu
- Word count: 4
- Vowels count: 5
- Consonants count: 3


3. Дан  список  чисел.  Посчитайте,  сколько  в  нем  пар  элементов,
равных друг  другу. Считается, что любые два элемента, равные друг
другу образуют одну пару, которую необходимо посчитать

In [ ]:
def task1_3():
    print("Task 1.3")
    print("-" * 36)
    numbers_str = input().split()
    numbers = [int(number) for number in numbers_str]
    unique_numbers = []
    pairs_counter = 0
    for number in numbers:
        if number not in unique_numbers:
            unique_numbers.append(number)
            number_count = numbers.count(number)
            if number_count > 1:
                pairs_counter += ((number_count - 1) * number_count) / 2
    print(int(pairs_counter))

task1_3()

Task 1.3
------------------------------------
5 5 2 1 4
1


4. Дана строка в виде случайной последовательности чисел от 0 до 9
Требуется  создать  словарь,  который  в  качестве  ключей  будет
принимать  данные  числа  (т.  е.  ключи  будут  типом  int),  а  в  качестве
значений – количество этих чисел в имеющейся последовательности.

In [ ]:
def task1_4():
    print("Task 1.4")
    print("-" * 36)
    sequence = input()
    result_dict = {}

    for char in sequence:
        digit = int(char)
        if digit in result_dict:
            result_dict[digit] += 1
        else:
            result_dict[digit] = 1

    print(result_dict)

task1_4()

Task 1.4
------------------------------------
2948093
{2: 1, 9: 2, 4: 1, 8: 1, 0: 1, 3: 1}


5. Реализуйте  программу  «Магазин  автозапчастей»,  которая  будет
включать в себя шесть пунктов меню.  У вас есть словарь, где ключ –
название  продукции.  Значение  – список,  который  содержит  состав
продукции, цену и кол-во (шт),которое есть в магазине.  
  1) Просмотр описания: название – описание
  2) Просмотр цены: название – цена.
  3) Просмотр количества: название – количество.
  4) Всю информацию.
  5) Покупка
В  пункте  «Покупка»  необходимо  совершить  покупку,    с
клавиатуры вводите название продукции и его кол-во, n – выход из
программы. Посчитать цену выбранных товаров и сколько товаров
осталось в изначальном списке
  6) До свидания

In [ ]:
def task1_5():
    print("Task 1.5")
    print("-" * 36)
    auto_parts = {
        "part A": ["descr A", 10, 10],
        "part B": ["descr B", 20, 20],
        "part C": ["descr C", 30, 30],
        "part D": ["descr D", 40, 40],
        "part E": ["descr E", 50, 50],
    }
    exit_flag = False
    while not exit_flag:
        action = int(input("Menu:\n - 1. View descriptions\n - 2. View prices\n - 3. View amount\n - 4. View al info\n - 5. Buy\n - 6. Leave\n Choose option: "))
        if not 1 <= action <= 6:
            print("Wrong input. Try again")
            continue
        match action:
            case 1:
                view_parts_descriptions(auto_parts=auto_parts)
            case 2:
                view_parts_prices(auto_parts=auto_parts)
            case 3:
                view_parts_amount(auto_parts=auto_parts)
            case 4:
                view_parts_full_info(auto_parts=auto_parts)
            case 5:
               auto_parts = buy_parts(auto_parts=auto_parts)
            case 6:
                exit_flag = True

def view_parts_descriptions(auto_parts):
    for name, info in auto_parts.items():
        print(f"{name} -- {info[0]}")

def view_parts_prices(auto_parts):
    for name, info in auto_parts.items():
        print(f"{name} -- {info[1]}")

def view_parts_amount(auto_parts):
    for name, info in auto_parts.items():
        print(f"{name} -- {info[2]}")

def view_parts_full_info(auto_parts):
    print(f"{'Name':^20}{'Description':^30}{'Price':^5}{'Amount':^8}")
    for name, info in auto_parts.items():
        print(f"{name:^20}{info[0]:^30}{info[1]:^5}{info[2]:^8}")

def buy_parts(auto_parts):
    parts_to_buy = {}
    parts_buy_exit_flag = False
    while not parts_buy_exit_flag:
        name = input("Enter name of the position: ")
        if not name in auto_parts:
            if name == 'n':
                parts_buy_exit_flag = True
            else:
                print("There is no such position. Try again")
            continue
        if name not in parts_to_buy:
            parts_to_buy[name] = [0, 0]
        item = auto_parts.get(name)
        parts_to_buy[name][1] = item[2]
        amount = int(input("Enter amount of items: "))
        if amount > item[2]:
            print("There are not that many items. We'll count all of them")
        amount = min(amount, item[2])
        parts_to_buy[name][0] += amount
        item[2] -= amount
    total_cost = 0
    print(f"{'Name':^20}{'Amount':^6}{'For all':^10}")
    for name, item in parts_to_buy.items():
        cost = item[0] * item[1]
        total_cost += cost
        print(f"{name:^20}{item[0]:^6}{cost:^10}")
    print("-" * 36)
    print(f"{'Total':^20}{total_cost:^16}")
    return auto_parts

task1_5()

Task 1.5
------------------------------------
Menu:
 - 1. View descriptions
 - 2. View prices
 - 3. View amount
 - 4. View al info
 - 5. Buy
 - 6. Leave
 Choose option: 4
        Name                 Description          Price Amount 
       part A                  descr A             10     10   
       part B                  descr B             20     20   
       part C                  descr C             30     30   
       part D                  descr D             40     40   
       part E                  descr E             50     50   
Menu:
 - 1. View descriptions
 - 2. View prices
 - 3. View amount
 - 4. View al info
 - 5. Buy
 - 6. Leave
 Choose option: 6


6. Дан  кортеж  целых  чисел.  Найти  индекс  первого  отрицательного
элемента.

In [ ]:
def task1_6():
    print("Task 1.6")
    print("-" * 36)
    numbers_str = input().split()
    numbers = [int(number) for number in numbers_str]
    numbers = tuple(numbers)
    for i in range(len(numbers)):
        if numbers[i] < 0:
            print(f"Index of the 1st negative number: {i}")
            break

task1_6()

Task 1.6
------------------------------------
1 2 3 3 4 -10  3 -1
Index of the 1st negative number: 5


### Часть 2
1.  Написать функцию для вычисления факториала числа.

In [ ]:
def task2_1():
    num = int(input("Enter number: "))
    print(get_fact(num))

def get_fact(num):
    if num < 0:
        return 0
    if num == 0:
        return 1
    if num == 1 or num == 2:
        return num
    return fact_tree(2, num)

def fact_tree(l, r):
    if(l > r):
        return 1
    if (l == r):
        return l
    if (r - l == 1):
        return l * r
    m = int((l+r) / 2)
    return fact_tree(l, m) * fact_tree(m + 1, r)

task2_1()

Enter number: 6
720


2. Напишите функцию, которая будет принимать один аргумент. Если в
функцию передаётся список, найти сумму отрицательных  чисел. Удалить из
списка все повторяющиеся элементы.  
 Если множество, посчитать количество слов.
Число – определить простое, или нет.
Строка  –  найти  количество  гласных  и  согласных.  Определить  самое
длинное слово.
Сделать проверку со всеми этими случаями.

In [ ]:
def task2_2():
    test_data = {
        'list': [1, -2, 3, -4, 5, -2, 3, 1],
        'set': {"word1", "word2", "word3", "word4"},
        'number_int': 17,
        'number_float': 15.0,
        'number_prime': 29,
        'number_not_prime': 9,
        'string': "Hello world programming",
        'string_empty': ""
    }
    for name, data in test_data.items():
        result = process_task2_2(data)
        print(f"- {name}: {data}")
        for key, value in result.items():
            print(f"  {key}: {value}")

def process_task2_2(arg):
    # list
    if isinstance(arg, list):
        # find the sum of negative numbers
        negative_sum = sum(num for num in arg if isinstance(num, (int, float)) and num < 0)
        unique_items = []
        for item in arg:
            if item not in unique_items:
                unique_items.append(item)
        return {
            'type' : 'list',
            'negative_sum' : negative_sum,
            'unique_items': unique_items
        }
    # set
    elif isinstance(arg, set):
        return {
            'type' : 'set',
            'words_count': len(arg)
        }
    # number: int -> is prime?
    elif isinstance(arg, int):
        is_prime = False
        if arg <= 1:
            is_prime = False
        elif arg == 2:
            is_prime = True
        elif arg % 2 == 0:
            is_prime = False
        else:
            is_prime = True
            arg_sqrt = int(round(math.sqrt(arg)))
            for i in range(3, arg_sqrt + 1, 2):
                if arg % i == 0:
                    is_prime = False
                    break
        return {
            'type': 'integer',
            'is_prime': is_prime
        }
    elif isinstance(arg, float):
        return {
            'type': 'float',
            'is_prime': 'False'
        }
    elif isinstance(arg, str):
        vowels = {'a', 'e', 'i', 'o', 'u'}
        consonants = {'b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'q', 'r', 's', 't', 'v', 'w', 'x', 'z'}
        consonants_num = 0
        vowels_num = 0
        words = re.split(r'[.,!?()\[\]|/\\\s]+', arg)
        words = [word for word in words if word]
        if len(words) == 0:
            return {
                'result': 'empty line'
            }
        for word in words:
            for letter in word:
                letter = letter.lower()
                if letter in vowels:
                    vowels_num += 1
                elif letter in consonants:
                    consonants_num += 1
        max_word_len = max(words, key = len)
        return{
            'consonants_num': consonants_num,
            'vowels_num' : vowels_num,
            'max_word_len' : max_word_len
        }
    else:
        return {
            'type' : 'unknown'
        }

task2_2()

- list: [1, -2, 3, -4, 5, -2, 3, 1]
  type: list
  negative_sum: -8
  unique_items: [1, -2, 3, -4, 5]
- set: {'word4', 'word2', 'word3', 'word1'}
  type: set
  words_count: 4
- number_int: 17
  type: integer
  is_prime: True
- number_float: 15.0
  type: float
  is_prime: False
- number_prime: 29
  type: integer
  is_prime: True
- number_not_prime: 9
  type: integer
  is_prime: False
- string: Hello world programming
  consonants_num: 15
  vowels_num: 6
  max_word_len: programming
- string_empty: 
  result: empty line


3. Проверить,  все  ли  строки  матрицы  содержат  хотя  бы  один
положительный элемент. Если да, то изменить знаки всех элементов матрицы
на обратные.

In [ ]:
def task2_3():
    n = random.randint(1, 5)
    m = random.randint(1, 5)
    matrix = np.random.randint(-10, 10, (n, m))
    print(matrix)
    for line in matrix:
        result = any(num > 0 for num in line)
        if not result:
            print(f"Line without positive numbers: {line}")
            break
    matrix = matrix * (-1)
    print(f"Each line contains a positive number\n {matrix}")

task2_3()

[[ -7  -5  -3]
 [-10   0   2]
 [ -4   8 -10]
 [  9   0  -8]
 [  5   2   5]]
Line without positive numbers: [-7 -5 -3]
Each line contains a positive number
 [[ 7  5  3]
 [10  0 -2]
 [ 4 -8 10]
 [-9  0  8]
 [-5 -2 -5]]


4. Напишите программу, демонстрирующую работу try\except\finally

In [ ]:
def task2_4():
    print()
    secret_number = random.randint(1,20)
    attempts = 3
    attempt = 1
    loser_flag = False
    try:
        while attempt <= attempts:
            print(f"- Attempt {attempt}/{attempts}")
            try:
                guess = int(input("- Enter number: "))
                if guess == secret_number:
                    print("- Ok, fine, you're  right.")
                    return
                if guess > secret_number:
                    print("- The secret number is even smaller than your chanses of winning")
                    attempt += 1
                else:
                    print("- The secret number is as far from you as the moon is")
                    attempt += 1
                print()
            except ValueError:
                if not loser_flag:
                    print("- Are you stupid? You need to enter a number\n- I forgive you for the first time\n")
                    loser_flag = True
                else:
                    attempt +=1
                    print("- I warned you. -1 attempt\n")

        raise Exception("Attempts are over")
    except Exception as e:
        if "Attempts are over" in str(e):
            print(f"- You are definitaly stupid\n- I thought of a number {secret_number}")
        else:
            print("- Unforeseen error\n- Either you are clumsy or I am stupid\n- I am inclined to the first option.")
    finally:
        print("\n--- GAME OVER ---\n")

task2_4()


- Attempt 1/3
- Enter number: 3
- The secret number is as far from you as the moon is

- Attempt 2/3
- Enter number: 10
- The secret number is as far from you as the moon is

- Attempt 3/3
- Enter number: 19
- The secret number is even smaller than your chanses of winning

- You are definitaly stupid
- I thought of a number 15

--- GAME OVER ---



### Часть 3
1. Класс Example. В нём пропишите 3 (метода) функции.  
Две  переменные  задайте  статически,  две  динамически.
Первый метод:  создайте  переменную  и  выведите  её.
Второй  метод:  верните  сумму  2-ух  глобальных  переменных.
Третий  метод:  верните  результат  возведения  первой  динамической
переменной  во  вторую  динамическую  переменную.
Создайте объект класса. Напечатайте оба метода. Напечатайте переменную a.

In [38]:
from example import Example
from countries_manager import Countries_manager
from stationery import Stationery, Pen, Pencil, Handle
from dice import Dice

In [ ]:
def task3_1():
    example = Example(5, 2)
    example.create_local_var()
    example.sum_global_vars()
    example.pow_dynamic_vars()

task3_1()

2. Создать класс Country: Столица, Площадь, Численность населения.
Создать список объектов. Вывести:
a)    список стран по заданной площади;
b)    список стран по заданной численности населения.

In [36]:
def task3_2():
    c_manager = Countries_manager()
    c_manager = create_countries(c_manager)
    c_manager.show_countries()
    try:
        filter_num = int(input("- 1. Filter by area\n- 2. Filter by population\n--- Choose filter: "))
        match filter_num:
            case 1:
                min_area = int(input("Enter min area: "))
                max_area = int(input("Enter max area:" ))
                result = c_manager.get_countries_by_area(min_area, max_area)
                show_results(result)
            case 2:
                min_population = int(input("Enter min population: "))
                max_population = int(input("Enter max population:" ))
                result = c_manager.get_countries_by_population(min_population, max_population)
                show_results(result)
            case _:
                print("Next time choose another option")
    except ValueError as e:
        print(e)

def create_countries(c_manager):
    c_manager.add_country("The North 🐺", "Winterfell", 3500030, 2190073)
    c_manager.add_country("Marley 💣", "Liberio", 3100086, 35004371)
    c_manager.add_country("Nilfgaard 🌞", "Nilfgaard City", 2200190, 14719205)
    c_manager.add_country("Earth Kingdom 🐉", "Ba Sing Se", 4508900, 68000912)
    c_manager.add_country("Durmstrang Territory 🦅", "Durmstrang Castle", 180000, 8000)
    c_manager.add_country("Narnia 🦁", "Cair Paravel", 947801, 367997)
    return c_manager

def show_results(result):
    print("-" * 80)
    print(f"{'Name':^25}{'Capital':^25}{'Area (km^2)':^15}{'Population':^15}")
    print("-" * 80)
    for country in result:
        print(f"{country.name:^25}{country.capital:^25}{country.area:^15}{country.population:^15}")
    print("-" * 80)
    print()

task3_2()

--------------------------------------------------------------------------------
          Name                    Capital           Area (km^2)    Population   
--------------------------------------------------------------------------------
       The North 🐺              Winterfell            3500030        2190073    
        Marley 💣                  Liberio             3100086       35004371    
       Nilfgaard 🌞            Nilfgaard City          2200190       14719205    
     Earth Kingdom 🐉            Ba Sing Se            4508900       68000912    
 Durmstrang Territory 🦅      Durmstrang Castle        180000          8000      
        Narnia 🦁               Cair Paravel           947801         367997     
--------------------------------------------------------------------------------

- 1. Filter by area
- 2. Filter by population
--- Choose filter: 2
Enter min population: 500000
Enter max population:1000000
----------------------------------------------------------------

3. Реализовать класс Stationery (канцелярская принадлежность). Определить  в  нём  атрибут  title  (название)  и  метод  draw  (отрисовка).  Метод выводит  сообщение  «Запуск  отрисовки»;  создать  три  дочерних  класса  Pen (ручка),  Pencil  (карандаш),  Handle  (маркер);  в  каждом  классе  реализовать переопределение  метода  draw.  Для  каждого  класса  метод  должен  выводить уникальное  сообщение; создать  экземпляры  классов  и  проверить,  что выведет описанный метод для каждого экземпляра.

In [37]:
def task3_3():
    pen = Pen("La Modernista Diamonds")
    pencil = Pencil("Slingshot-Pencil")
    handle = Handle("PONY")
    pen.draw()
    pencil.draw()
    handle.draw()

task3_3()

Drawing horse with a pen
Solving sudoku with a pencil
Highlight quotes with a handle


4. Придумать  класс  самостоятельно, реализовать  в  нем  методы  экземпляра
класса, статические, методы, методы класса.

In [41]:
def task3_4():
    dice1 = Dice("green")
    dice2 = Dice("blue")
    Dice.print_rules()
    print("-" * 25)
    print(f"{'Dice':^6}|{'Sides':^7}|{'Last Roll':^12}")
    print("-" * 25)
    dice2.roll()
    print(f"{'1':^6}|{dice1.sides:^7}|{dice1.last_roll:^12}")
    print(f"{'2':^6}|{dice2.sides:^7}|{dice2.last_roll:^12}")
    print("-" * 25)
    dice1.change_sides(4)
    print(f"{'1':^6}|{dice1.sides:^7}|{dice1.last_roll:^12}")
    print(f"{'2':^6}|{dice2.sides:^7}|{dice2.last_roll:^12}")
    print("-" * 25)
    dice1.roll()
    print(f"{'1':^6}|{dice1.sides:^7}|{dice1.last_roll:^12}")
    print(f"{'2':^6}|{dice2.sides:^7}|{dice2.last_roll:^12}")
    print("-" * 25)
    Dice.change_sides(3)
    print(f"{'1':^6}|{dice1.sides:^7}|{dice1.last_roll:^12}")
    print(f"{'2':^6}|{dice2.sides:^7}|{dice2.last_roll:^12}")
    print("-" * 25)

task3_4()

+ RULES:
- Single 1 = 100
- Single 5 = 50
- Three 1s = 300
- Three 2s = 200
- Three 3s = 300
- Three 4s = 400
- Three 5s = 500
- Three 6s = 6
-------------------------
 Dice | Sides | Last Roll  
-------------------------
  1   |   3   |     0      
  2   |   3   |     2      
-------------------------
  1   |   4   |     0      
  2   |   4   |     2      
-------------------------
  1   |   4   |     4      
  2   |   4   |     2      
-------------------------
  1   |   3   |     4      
  2   |   3   |     2      
-------------------------
